package com.naman.hms.enums;

public enum Specialization {
    CARDIOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC_SURGEON,
    PEDIATRICIAN,
    GENERAL_PHYSICIAN,
    RADIOLOGIST,
    SURGEON,
    EMERGENCY_PHYSICIAN,
    DERMATOLOGIST,
    PSYCHIATRIST,
    ONCOLOGIST,
    GYNECOLOGIST,
    ANESTHESIOLOGIST
}